AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    # HelloWorldFunction:
    #     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    #     Properties:
    #         CodeUri: hello_world/build
    #         Handler: app.lambda_handler
    #         Runtime: python3.6
    #         Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
    #             Variables:
    #                 PARAM1: VALUE
    #         Events:
    #             HelloWorld:
    #                 Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
    #                 Properties:
    #                     Path: /hello
    #                     Method: get

    TrainTicTacToe:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: tictactoe/build
            Handler: ttt.train
            Runtime: python3.6
            Timeout: 30
            Events:
                Train:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /train
                        Method: get

            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ALLOW_ORIGIN: http://localhost:8080


    NextMoveTicTacToe:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: tictactoe/build
            Handler: ttt.nextMove
            Runtime: python3.6
            Timeout: 30
            Events:

                NextMove:
                    Type: Api
                    Properties:
                        Path: /next-move
                        Method: get

            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ALLOW_ORIGIN: http://localhost:8080

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn



